name: model-training
on: []
jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: iterative/setup-cml@v2
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python get_data.py
          python train.py

          cat metrics.txt >> report.md
          echo '![](./confusion_matrix.png "Confusion Matrix")' >> report.md
          cml comment create report.md
